name: jserializer
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: '>=1.0.0 <2.0.0'
  type_plus: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1


