name: jserializer_generator
description: A starting point for Dart libraries or applications.
version: 1.1.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build_runner: ">=2.4.4<3.0.0"
  code_builder: ">=4.5.0<5.0.0"
  merging_builder:
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: merging_builder/
  source_gen: ^2.0.0
  jserializer:
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: jserializer/
  build: ^2.4.1
  dart_style: ^3.0.1
  fpdart: ">=1.1.0<2.0.0"
  change_case: ^2.0.1
  barbecue: ^0.5.0
  collection: ^1.17.1
  path: ^1.9.0
