name: jserializer_generator
description: A starting point for Dart libraries or applications.
version: 1.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  analyzer: ">=2.4.0 <5.0.0"
  build_runner: ^2.1.5
  code_builder: ^4.1.0
  merging_builder:
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: merging_builder/
  source_gen: ^1.1.1
  jserializer:
#    path: ../jserializer/
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: jserializer/
  build: ^2.1.1
  dart_style: ^2.2.0
  fpdart: ^0.0.12
  change_case: ^1.0.1
  barbecue: ^0.4.0
  collection: ^1.16.0
