name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner:
  jserializer_generator:
    path: ../../jserializer_generator

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  benchmark_harness: ^2.0.0
  benchmark: ^0.3.0
  pure: ^0.1.1
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  build_web_compilers: any
  fpdart: ">=1.1.0<2.0.0"
  jserializer:
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: jserializer/

