name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner:
#  jserializer_generator:
#    path: ../../jserializer_generator
  jserializer_generator:
    git:
      url: git@github.com:erabti/jserializer_library.git
      path: jserializer_generator/

dependencies:
  flutter:
    sdk: flutter
  benchmark_harness: ^2.0.0
  dart_json_mapper:
  benchmark: ^0.3.0
  pure: ^0.1.1
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  build_web_compilers: any