name: merging_builder

description: MergingBuilder reads several input files and writes merged output
  to one file. StandaloneBuilder enables output to a custom folder with custom
  output file name.

version: 0.2.3

homepage: https://github.com/simphotonics/merging_builder

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build: ^2.4.1
  build_runner: ">=2.4.4<3.0.0"
  dart_style: ^3.0.1
  directed_graph: ^0.4.3
  exception_templates: ^0.3.1
  file: ^7.0.0
  glob: ^2.1.1
  lazy_memo: ^0.2.3
  meta: ^1.3.0
  path: ^1.8.3
  quote_buffer: ^0.2.3
  source_gen: ^2.0.0

# source_gen:
#   git:
#     url: git@github.com:dart-lang/source_gen.git
#     ref: master
#     path: source_gen
dev_dependencies:
  build_test: ^2.1.7
  crypto: ^3.0.3
  lints: ^2.1.0
  test: ^1.24.2
